project:
  type: website
  output-dir: _site

website:
  title: "Nathan Irizarry | Product Portfolio"
  favicon: images/prototyping-favicon.png
  navbar:
    background: light
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Projects
        menu:
          - href: projects/project-1.qmd
            text: ExperienceLink
          - href: projects/project-2.qmd
            text: Business Case Presentation
          - href: projects/project-3.qmd
            text: Project 3

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    anchor-sections: false
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;600;700&family=Inter:wght@300;400;500;600&display=swap" rel="stylesheet">
